### ISSUE TITLE
Temporary Homepage Display

### ISSUE THREAD

**Issue by Tor020** [DevvitIO/DevvitIO.github.io#11]
[Live Display](https://tor020.github.io/temphome/)

[Development Branch ](https://github.com/Tor020/Devvit_2.0)

Feel free to leave any bugs / suggestions / feedback on this issue
- **Please specify if it's a bug / suggestion / feedback**  so that I don't get confused

**Comment by Tor020** [comment]
Feel free to drop any feedback / suggestions here.

**Comment by KenavR** [comment]
Copied from Discord:

I have some feedback:

1. I think it is too "colorful". What I mean by that is that the colors (projects, multiple discord colors, default links) seem random and not thought out.
1. Inconsistent Fonts
1. Multiple ways to Join the server, why have both buttons?
1. That may be only my issue, but the asymmetry between flowchart and Discords seems odd
1. I get what you were going for with the checkboxes, but I am not sure if it works when it doesn't do anything while clicking them
1. It has some issues on mobile (inconsistent content padding, chart and discords stays in the same row - neither of it readable, project cards are not filling the entire width)
1. Maybe a stock image as BG or something would be nice, the white looks "boring"

Today I am really busy, but I will make a couple of PRs tomorrow with fixes that I think absolutely have to be done (mobile stuff, font) and different ones with my suggestions

**Comment by Tor020** [comment]
1, 2, 3, 5 are just things i haven't gotten around to addressing, like i said it's not done yet. However there should be two fonts. Nunito for headlines, Roboto for content

4. is obnoxious svg bs that I need to figure out still. I've been tweaking that shit, but it's been very uncooperative

6. I hate doing responsive stuff, so if you wanna submit a pr about that it'd be helpful

7.  Not sure I really agree, but I'll consider it. I think i might just change the default white BG to something slightly darker. But I don't want arbitrary stock image filler. Like i said though, it's not done. I had planned on animating the pieces of the logo

**Comment by Tor020** [comment]
https://github.com/DevvitIO/Devvit_2.0 new Repo
